# Use uv's official Python image as base
# https://github.com/astral-sh/uv/pkgs/container/uv/579620319?tag=python3.13-bookworm
FROM ghcr.io/astral-sh/uv:python3.13-bookworm

# set labels
LABEL org.opencontainers.image.description="A scraper ETL pipeline for French mobile phone plans."
LABEL org.opencontainers.image.licenses="tagny"
LABEL org.opencontainers.image.source="https://github.com/tagny/quechoisir-comparator-scrapers/mobile_phone_plans"
LABEL org.opencontainers.image.title="quechoisir-mobile-phone-plans-etl"
LABEL org.opencontainers.image.url="https://github.com/tagny/quechoisir-comparator-scrapers/mobile_phone_plans/Dockerfile"
LABEL org.opencontainers.image.version="0.1.0"
LABEL org.opencontainers.image.vendor="tagny"
LABEL org.opencontainers.image.authors="tagny https://github.com/tagny"


# install the chrome web driiver
RUN apt update -y && \
    mkdir -p /var/lib/apt/lists/partial && \
    apt install -y --no-install-recommends libsm6 libxext6 ffmpeg libfontconfig1 libxrender1 libgl1-mesa-glx && \
    apt -y --force-yes install --no-install-recommends libu2f-udev fonts-liberation libasound2  libatk-bridge2.0-0 libatk1.0-0  libatspi2.0-0  libcairo2 libcups2 libdrm2 libgbm1 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libx11-6 libxcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxkbcommon0 libxrandr2 xdg-utils && \
    apt -y --force-yes install --no-install-recommends wget && \
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    dpkg -i google-chrome-stable_current_amd64.deb && \
    apt install -f --no-install-recommends && \
    rm google-chrome-stable_current_amd64.deb && \
    apt autoremove -y && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy application code
COPY etl ./etl

# Copy pyproject.toml and README.md for dependency resolution
COPY pyproject.toml README.md ./

# Copy configuration files
COPY config ./config

# create app user
RUN useradd -ms /bin/bash app
RUN chown app:app /app
USER app

# Install project dependencies
RUN uv sync && uv cache clean

# Set default environment variables
ENV PROJECT_ID=""
ENV DATASET=""
ENV BUCKET_NAME=""
ENV RAW_BASE_DIR=".data/quechoisir-comparators-data/mobile-phone-plans/raw"
ENV TRANSFORMED_BASE_DIR=".data/quechoisir-comparators-data/mobile-phone-plans/transformed"
ENV BASE_URL="https://www.quechoisir.org/comparateur-forfait-mobile-n43896/"

# Run the server with customizable args from env vars
ENTRYPOINT ["sh", "-c"]
CMD ["uv run -m etl"]
